### ISSUE TITLE
Documentation Concerns

### ISSUE THREAD

**Issue by ghost** [AWSW-Modding/AWSW-Modtools#2]
First off, the new documentation is fucking beautiful. Nice job on that one. 

However, looking at the gh-pages branch, I can't help but feel that it's a little bit complex. All the documentation should be files should be in their own folder, for one. Too many root files will make the loader a pain to update. 

I don't really have an issue with having to build the docs, as that's something only contributors will do anyway, but I am worried about how they are presented in the repo's root. A user shouldn't have to click another link to read preliminary information about the software, so there probably should at least be a project name and abstract in README.md. 

One more thing: I think some information was lost in the transition. Some of the sectional headers aren't the proper size, and I think some of the mod developing help is missing.

**Comment by scrlys** [comment]
Sorry about the delay, I guess I wasn't notified about this issue opening. This shouldn't happen again.

As for the gh-branch issue: I was planning on it to be hosted via GitHub pages so we don't have to worry about an actual host. However, there are three options where we can serve files from: the master branch, the master branch's docs/ folder, and the gh-pages branch. After unsuccessfully trying to work past that with symbolic links, I decided to end up building everything in the gh-pages branch. If someone can figure out a better way, let me know.

Because I settled with gh-pages branch, it serves them in the repo's root, so I had to build there. Anyways, the user should not download any other branch except for master or develop because there might be broken features. I agree, though, with more information in README.md

I understand that I may have skipped over some information. If you want to add or change the documentation, either make a pull request (can you fork a fork, even if you're the original repo's author?) or open a new issue.

**Comment by Londynbird11** [comment]
First off whoever has done this BULLSHIT to my account can fucking stop!!! It has me n my "bf" fighting bc I know he's doing all this shit right hear to me but I think he failed to remember all the details of how to do it n thinks I'm stupid first off and can't figure it out 2nd he's trying to cover his ass bc he cheated !!!! I caught him !! 3rd thing... now I pay my own phone internet ext .. in which he would have no clue on how to do... my internet whatever proxy accounts cell photos all gone n deleted!!! I don't have the time to bs w this crap n I would greatly appriciate it if someone could help me for once in this situation n turn it around on him!!! But twice as hard!! Plz message me if u can help at erinbyrd1125@gmail.com  it would be greatly appreciated!! I would put out my number but not here!!! Ty very much if ur able to help n clean this mess up!!! 
                Erin byrd
