### ISSUE TITLE
Current develop-branch only compatible with Windows

### ISSUE THREAD

**Issue by consolethinks** [AWSW-Modding/AWSW-Modtools#94]
The bootstrap.rpy checks whether the system is Windows, if not, it does nothing. When I remove the "if renpy.windows:" line, the game constantly restarts in the background without opening a window. 

This is caused by the windows dependent implementation of ssl which is downloaded automatically with Steam (into game/steam_workshop) regardless of platform. If I disable ssl in the code by commenting out the lines 212-222 in modconfig.py, the modloader works as intended.

**Comment by muddyfish** [comment]
On removing the Windows check, I'm getting an error about gpg not being found. I'll fix that as well after I can verify SSL is being an issue

**Comment by muddyfish** [comment]
As a write up, the following are currently issues:
 - The modtools explicitly check to not work on Windows
 - The game checks for GPG for Steam stuff - not required yet so can be commented out
 - The game fails to import _ssl
   - This is required for the ingame mod downloader

Should be fixed in https://github.com/AWSW-Modding/AWSW-Modtools/pull/95
